package com.mc_custom.classes.listeners.abilities;

public enum AbilityType {
	AQUA_AFFINITY(1),
	ARROW_SPLASH(2),
	CRAFT_BAT(3),
	CRAFT_EGG(4),
	CRAFT_HORSE_ARMOR(5),
	CRAFT_ICE(6),
	CRAFT_NAMETAG(7),
	CRAFT_VILLAGER(8),
	CRITICAL_HIT(9),
	DROWN_IMMUNITY(10),
	FAST_BONEMEAL(11),
	FIRE_BREATH(12),
	FLIGHT(13),
	FOOD_REGEN(14),
	IMPERSONATE(15),
	INCREASE_DAMAGE_FIRE(16),
	INCREASE_DAMAGE_SELF(17),
	INCREASE_XP(18),
	LAVA_IMMUNITY(19),
	LIFE_STEAL(20),
	MOBILE_BREWING(21),
	MOBILE_SMELTING(22),
	NEGATE_FALL(23),
	NIGHT_STALKER(24),
	NIGHT_VISION(25),
	NO_HEALTH_REGEN(26),
	POTION_BOOST(27),
	REDUCE_DAMAGE_SELF(28),
	RETALIATE(29),
	SNOWBALL_DAMAGE(30),
	STACKABLE_POTS(31),
	SWIM(32),
	TALONS(33),
	TELEPORT(34),
	TIME_CHANGE(35),
	WEATHER_CHANGE(36),
	WORKBENCH(37),
	LEVITATE(38);
	private final int id;

	AbilityType(int id) {
		this.id = id;
	}

	public int getId(AbilityType ability) {
		return id;
	}
}